apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    actions:
      1:
        action: {{.Values.action}}
        description: >-
          Delete indices older than 14 (default) days and prefixed with logstash-.
          Ignore the error if the filter does not result in an actionable
          list of indices (ignore_empty_list) and exit cleanly.
        options:
{{ toYaml .Values.options | indent 10 }}
        filters:
{{ toYaml .Values.logstashFilters | indent 10 }}
      2:
        action: {{.Values.action}}
        description: >-
          Delete indices older than 14 (default) days and prefixed with logsystemd-.
          Ignore the error if the filter does not result in an actionable
          list of indices (ignore_empty_list) and exit cleanly.
        options:
{{ toYaml .Values.options | indent 10 }}
        filters:
{{ toYaml .Values.logsystemdFilters | indent 10 }}


  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
{{ toYaml .Values.client | indent 6 }}
    logging:
{{ toYaml .Values.logging | indent 6 }}
