apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{.Values.name}}
spec:
  schedule: {{.Values.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.name}}
            image: "{{ .Values.image }}"
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            env:
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "fullname" . }}-auth
            - name: ES_PW
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "fullname" . }}-auth
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
            resources:
              limits:
                cpu: 50m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 200Mi
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
