# Default values for curator.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image: quay.io/samsung_cnct/curator:v3
name: curator
namespace: kube-logging
schedule: "30 3 * * *"
